### ISSUE TITLE
Suggested Change to how Nightmare prototype is changed?

### ISSUE THREAD

**Issue by TheTechChild** [unlight/nightmare-xpath#4]
Hey I love this package and that I can select off the xpath of an element. However, I happen to use a lot of different modules that modify the Nightmare instance that I use to scrape, and it's hard to remember how all the different packages change the Nightmare class. instead of doing the following:
```
var Nightmare = require("nightmare");
// all the function definitions
Nightmare.prototype.xpath = function(selector, handler) {}
```
Maybe it could be changed to the following:
```
module.exports = exports = function(Nightmare) {
  // all the function definitions
  Nightmare.prototype.xpath = function(selector, handler) {}
}
```
Without the change, my require statements look like the following:
```
/** Require in all my node modules and npm modules **/
// Most of the work I do for my clients is scraping portals, downloading files, and other sundry task automation that they need but don't want to do so I use packages like csvtojson, url parsers, path, promisify, etc. so the require statements are usually long

/** Build the Nightmare Instance that I want to Use **/
let Nightmare = require('Nightmare');
Nightmare = require('some-other-nightmare-pkg')(Nightmare);
require('nightmare-inline-download')(Nightmare);
require('nightmare-xpath');
```
It is frustrating to have to go and research how each particular module modifies Nightmare each time I am going to write a new scrape. If nightmare-xpath included the change above though then my require statements could be simplified a lot:
```
/** Require in my node and npm modules **/

/** Build the custom Nightmare for this particular scrape **/
const Nightmare = require('Nightmare');
require('some-other-nightmare-pkg')(Nightmare);
require('nightmare-inline-download')(Nightmare);
require('nightmare-xpath')(Nightmare);

// do scraping and automation task
```
Just a thought. Would you like me to put it in a pull request??

**Comment by unlight** [comment]
Is this recomended way of extending Nightmare?

**Comment by TheTechChild** [comment]
If you look at https://github.com/rosshinkley/nightmare-download-manager . That is the way that he extends the Nightmare prototype. Rosshinkley is the original owner of the Nightmare library, so I feel like his pattern is probably the "recommended" way. From his documentation of nightmare-download-manager:

Require the library and pass the Nightmare library as a reference to attach the plugin actions:

```
var Nightmare = require('Nightmare');
require('nightmare-download-manager')(Nightmare);
```

**Comment by unlight** [comment]
Ok, but if you ask me, it is still not clear was is going on in that way, still a side effect.
My preference is something like
```
Nightmare.prototype.xpath = require('nightmare-xpath/action')
```

**Comment by unlight** [comment]
I'll implement it at the weekend

**Comment by TheTechChild** [comment]
Okay thank you! Again, I really appreciate the work you put in to figure out how to get the selecting by xpath to work. It is marvelously helpful.
